#整合mybatis配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
#    username: root
#    password: 123456



#整合druid连接池
spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
#druid相关配置
    druid:
#监控统计拦截的filters
      filters: stat
#基本属性
      url: jdbc:mysql://127.0.0.1:3306/songhuale?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: 123456
#配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
#获取连接等待超时时间
      max-wait: 60000
#间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
#一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
#打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

#配置redis参数
  redis:
    database: 2
    host: 129.204.22.202
    port: 6379
    #user:
    #password:

#mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.springbootxianhualemaster.pojo

#控制台日志输出
logging:
  level:
    cn.springbootxianhualemaster.dao: DEBUG #放入需要打印日志的路径
    cn.springbootxianhualemaster.controller: DEBUG
#配置日志输出
  #config: classpath:config/logbackspring. xml
  #path: D:/logs/springboot



